spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/slug?characterEncoding=utf8&useSSL=true&zeroDateTimeBehavior=convertToNull
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
